version: 2

defaults: &defaults
  working_directory: ~/
  docker:
    - image: circleci/node:8.3.0

jobs:
  install:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn --network-timeout 600000
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

  lint:
    <<: *defaults
    steps:
      - run:
          name: Run ESLint
          command: yarn run lint

  test-unit:
    <<: *defaults
    steps:
      - run:
          name: Run unit tests
          command: yarn run test

workflows:
  version: 2
  lint-and-test:
    jobs:
      - install
      - lint:
          requires:
            - install
      - test-unit:
          requires:
            - install
